name: Container scan (On demand)

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: image tag
        required: true

jobs:
  scan:
    uses: bh-ent-tech/shared-workflows/.github/workflows/scan-container-image.yaml@main
    with:
        image_name: "ghcr.io/bh-ent-tech/cde-app-shell:${{ github.event.inputs.tag }}"
        username: 'paragwaghela-bh'
        check_for_input_files: true
    secrets:
        token: ${{ secrets.GH_TOKEN }}
